//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Web.PaymentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Common.Entities")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyersCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyersFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CvvCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpirationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentPurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellersCardNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyersCardNumber {
            get {
                return this.BuyersCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyersCardNumberField, value) != true)) {
                    this.BuyersCardNumberField = value;
                    this.RaisePropertyChanged("BuyersCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyersFullName {
            get {
                return this.BuyersFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyersFullNameField, value) != true)) {
                    this.BuyersFullNameField = value;
                    this.RaisePropertyChanged("BuyersFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CvvCode {
            get {
                return this.CvvCodeField;
            }
            set {
                if ((this.CvvCodeField.Equals(value) != true)) {
                    this.CvvCodeField = value;
                    this.RaisePropertyChanged("CvvCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationMonth {
            get {
                return this.ExpirationMonthField;
            }
            set {
                if ((this.ExpirationMonthField.Equals(value) != true)) {
                    this.ExpirationMonthField = value;
                    this.RaisePropertyChanged("ExpirationMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpirationYear {
            get {
                return this.ExpirationYearField;
            }
            set {
                if ((this.ExpirationYearField.Equals(value) != true)) {
                    this.ExpirationYearField = value;
                    this.RaisePropertyChanged("ExpirationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((this.PaymentAmountField.Equals(value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentPurpose {
            get {
                return this.PaymentPurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentPurposeField, value) != true)) {
                    this.PaymentPurposeField = value;
                    this.RaisePropertyChanged("PaymentPurpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellersCardNumber {
            get {
                return this.SellersCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SellersCardNumberField, value) != true)) {
                    this.SellersCardNumberField = value;
                    this.RaisePropertyChanged("SellersCardNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/PaymentService.Application.Dtos")]
    [System.SerializableAttribute()]
    public partial class PaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameStore.Web.PaymentService.PaymentStatus PaymentStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((this.PaymentIdField.Equals(value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameStore.Web.PaymentService.PaymentStatus PaymentStatus {
            get {
                return this.PaymentStatusField;
            }
            set {
                if ((this.PaymentStatusField.Equals(value) != true)) {
                    this.PaymentStatusField = value;
                    this.RaisePropertyChanged("PaymentStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/Common.Entities")]
    public enum PaymentStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardDoesNotExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConfirmationCodeIsNotCorrect = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionIdIsNotCorrect = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSupportedCard = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ConductPurchase", ReplyAction="http://tempuri.org/IPaymentService/ConductPurchaseResponse")]
        GameStore.Web.PaymentService.PaymentResponse ConductPurchase(GameStore.Web.PaymentService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ConductPurchase", ReplyAction="http://tempuri.org/IPaymentService/ConductPurchaseResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentResponse> ConductPurchaseAsync(GameStore.Web.PaymentService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ConfirmPayment", ReplyAction="http://tempuri.org/IPaymentService/ConfirmPaymentResponse")]
        GameStore.Web.PaymentService.PaymentResponse ConfirmPayment(int paymentId, string confirmationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/ConfirmPayment", ReplyAction="http://tempuri.org/IPaymentService/ConfirmPaymentResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentResponse> ConfirmPaymentAsync(int paymentId, string confirmationCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : GameStore.Web.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<GameStore.Web.PaymentService.IPaymentService>, GameStore.Web.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.Web.PaymentService.PaymentResponse ConductPurchase(GameStore.Web.PaymentService.Payment payment) {
            return base.Channel.ConductPurchase(payment);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentResponse> ConductPurchaseAsync(GameStore.Web.PaymentService.Payment payment) {
            return base.Channel.ConductPurchaseAsync(payment);
        }
        
        public GameStore.Web.PaymentService.PaymentResponse ConfirmPayment(int paymentId, string confirmationCode) {
            return base.Channel.ConfirmPayment(paymentId, confirmationCode);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentResponse> ConfirmPaymentAsync(int paymentId, string confirmationCode) {
            return base.Channel.ConfirmPaymentAsync(paymentId, confirmationCode);
        }
    }
}
